# Generated by Django 5.2.1 on 2025-07-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_wishlisted_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight",
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name="Name"
            ),
        ),
    ]
