# Generated by Django 5.2.1 on 2025-07-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_product_stock_remove_product_weight_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Name Category"
            ),
        ),
    ]
