# Generated by Django 5.2.1 on 2025-07-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_category_slug_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
