# Generated by Django 5.2.1 on 2025-07-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "القاهرة"),
                    ("GZ", "الجيزة"),
                    ("ALX", "الإسكندرية"),
                    ("ASN", "أسوان"),
                    ("AST", "أسيوط"),
                    ("BNS", "بني سويف"),
                    ("BH", "البحيرة"),
                    ("IS", "الإسماعيلية"),
                    ("MN", "المنيا"),
                    ("MNF", "المنوفية"),
                    ("MNFY", "المنوفية"),
                    ("MT", "مطروح"),
                    ("KFS", "كفر الشيخ"),
                    ("DK", "الدقهلية"),
                    ("SHG", "سوهاج"),
                    ("SHR", "الشرقية"),
                    ("PTS", "بورسعيد"),
                    ("DT", "دمياط"),
                    ("FYM", "الفيوم"),
                    ("GH", "الغربية"),
                    ("KB", "القليوبية"),
                    ("LX", "الأقصر"),
                    ("WAD", "الوادي الجديد"),
                    ("SUZ", "السويس"),
                    ("SIN", "شمال سيناء"),
                    ("SIS", "جنوب سيناء"),
                    ("QH", "قنا"),
                    ("RSH", "البحر الأحمر"),
                ],
                max_length=10,
                verbose_name="المحافظة",
            ),
        ),
    ]
