# Generated by Django 5.2.1 on 2025-07-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_governorate"),
        ("product", "0002_remove_product_wishlisted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="whishlist",
            field=models.ManyToManyField(
                blank=True, related_name="wishlists", to="product.product"
            ),
        ),
    ]
