# Generated by Django 5.2.1 on 2025-07-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_whishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="whishlist",
            new_name="wishlist",
        ),
    ]
