# Generated by Django 5.2.1 on 2025-07-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_whishlist_profile_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="second_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
