# Generated by Django 5.2.1 on 2025-07-20 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_second_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.RemoveField(
            model_name="profile",
            name="second_phone",
        ),
        migrations.AddField(
            model_name="profile",
            name="alternate_phone",
            field=models.CharField(
                blank=True,
                help_text="You can enter another Egyptian phone number for contact (optional).",
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with 010, 011, 012, or 015 and be 11 digits.",
                        regex="^(01[0125])[0-9]{8}$",
                    )
                ],
                verbose_name="Alternate Phone Number (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Please write your address in detail, e.g., district, building number, apartment number, street name, and any additional details to facilitate order delivery.",
                verbose_name="Detailed Address",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Cairo"),
                    ("GZ", "Giza"),
                    ("ALX", "Alexandria"),
                    ("ASN", "Aswan"),
                    ("AST", "Assiut"),
                    ("BNS", "Beni Suef"),
                    ("BH", "Beheira"),
                    ("IS", "Ismailia"),
                    ("MN", "Minya"),
                    ("MNF", "Monufia"),
                    ("MNFY", "Monufia"),
                    ("MT", "Matrouh"),
                    ("KFS", "Kafr El Sheikh"),
                    ("DK", "Dakahlia"),
                    ("SHG", "Sohag"),
                    ("SHR", "Sharqia"),
                    ("PTS", "Port Said"),
                    ("DT", "Damietta"),
                    ("FYM", "Fayoum"),
                    ("GH", "Gharbia"),
                    ("KB", "Qalyubia"),
                    ("LX", "Luxor"),
                    ("WAD", "New Valley"),
                    ("SUZ", "Suez"),
                    ("SIN", "North Sinai"),
                    ("SIS", "South Sinai"),
                    ("QH", "Qena"),
                    ("RSH", "Red Sea"),
                ],
                max_length=10,
                verbose_name="Governorate",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                help_text="Please enter an Egyptian phone number starting with 010, 011, 012, or 015.",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with 010, 011, 012, or 015 and be 11 digits.",
                        regex="^(01[0125])[0-9]{8}$",
                    )
                ],
                verbose_name="Primary Phone Number",
            ),
        ),
    ]
