# Generated by Django 5.2.1 on 2025-07-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profile_options_remove_profile_second_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Cairo"),
                    ("GZ", "Giza"),
                    ("ALX", "Alexandria"),
                    ("ASN", "Aswan"),
                    ("AST", "Assiut"),
                    ("BNS", "Beni Suef"),
                    ("BH", "Beheira"),
                    ("IS", "Ismailia"),
                    ("MN", "Minya"),
                    ("MNF", "Monufia"),
                    ("MT", "Matrouh"),
                    ("KFS", "Kafr El Sheikh"),
                    ("DK", "Dakahlia"),
                    ("SHG", "Sohag"),
                    ("SHR", "Sharqia"),
                    ("PTS", "Port Said"),
                    ("DT", "Damietta"),
                    ("FYM", "Fayoum"),
                    ("GH", "Gharbia"),
                    ("KB", "Qalyubia"),
                    ("LX", "Luxor"),
                    ("WAD", "New Valley"),
                    ("SUZ", "Suez"),
                    ("SIN", "North Sinai"),
                    ("SIS", "South Sinai"),
                    ("QH", "Qena"),
                    ("RSH", "Red Sea"),
                ],
                max_length=10,
                verbose_name="Governorate",
            ),
        ),
    ]
