# Generated by Django 5.2.1 on 2025-07-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0002_remove_product_wishlisted_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer", models.CharField(max_length=50, verbose_name="offer")),
                (
                    "image",
                    models.ImageField(
                        upload_to="featured_products/",
                        verbose_name="Large Banner Image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_entries",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured Product",
                "verbose_name_plural": "Featured Products",
            },
        ),
    ]
