# Generated by Django 5.2.1 on 2025-07-15 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0003_collection_is_offer"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer", models.CharField(max_length=50, verbose_name="offer")),
                (
                    "image",
                    models.ImageField(
                        upload_to="featured_collections/",
                        verbose_name="Large Banner Image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_entries",
                        to="features.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured Collection",
                "verbose_name_plural": "Featured Collections",
            },
        ),
    ]
