# Generated by Django 5.2.1 on 2025-07-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_featuredcollection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="featuredcollection",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Featured Collection",
                "verbose_name_plural": "Featured Collections",
            },
        ),
        migrations.AlterModelOptions(
            name="featuredproduct",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Featured Product",
                "verbose_name_plural": "Featured Products",
            },
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AddField(
            model_name="featuredproduct",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AddField(
            model_name="featuredproduct",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
    ]
