# Generated by Django 5.2.1 on 2025-07-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_featuredcollection_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeaturedCollection",
        ),
    ]
