# Generated by Django 5.2.1 on 2025-07-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#f5f5dc", "Beige"),
                            ("#000", "Black"),
                            ("#00f", "Blue"),
                            ("#a52a2a", "Brown"),
                            ("#ff7f50", "Coral"),
                            ("#00ffff", "Cyan"),
                            ("#ffd700", "Gold"),
                            ("#808080", "Gray"),
                            ("#0f0", "Green"),
                            ("#4b0082", "Indigo"),
                            ("#e6e6fa", "Lavender"),
                            ("#00ff00", "Lime"),
                            ("#ff00ff", "Magenta"),
                            ("#800000", "Maroon"),
                            ("#98ff98", "Mint"),
                            ("#000080", "Navy"),
                            ("#808000", "Olive"),
                            ("#ffa500", "Orange"),
                            ("#ffc0cb", "Pink"),
                            ("#800080", "Purple"),
                            ("#f00", "Red"),
                            ("#fa8072", "Salmon"),
                            ("#c0c0c0", "Silver"),
                            ("#008080", "Teal"),
                            ("#40e0d0", "Turquoise"),
                            ("#ee82ee", "Violet"),
                            ("#fff", "White"),
                            ("#ff0", "Yellow"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("#f5f5dc", "Beige"),
                            ("#000", "Black"),
                            ("#00f", "Blue"),
                            ("#a52a2a", "Brown"),
                            ("#ff7f50", "Coral"),
                            ("#00ffff", "Cyan"),
                            ("#ffd700", "Gold"),
                            ("#808080", "Gray"),
                            ("#0f0", "Green"),
                            ("#4b0082", "Indigo"),
                            ("#e6e6fa", "Lavender"),
                            ("#00ff00", "Lime"),
                            ("#ff00ff", "Magenta"),
                            ("#800000", "Maroon"),
                            ("#98ff98", "Mint"),
                            ("#000080", "Navy"),
                            ("#808000", "Olive"),
                            ("#ffa500", "Orange"),
                            ("#ffc0cb", "Pink"),
                            ("#800080", "Purple"),
                            ("#f00", "Red"),
                            ("#fa8072", "Salmon"),
                            ("#c0c0c0", "Silver"),
                            ("#008080", "Teal"),
                            ("#40e0d0", "Turquoise"),
                            ("#ee82ee", "Violet"),
                            ("#fff", "White"),
                            ("#ff0", "Yellow"),
                        ],
                        help_text="Text color for tag (e.g. #fff or 'red')",
                        max_length=20,
                        null=True,
                        verbose_name="Color",
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("#f5f5dc", "Beige"),
                            ("#000", "Black"),
                            ("#00f", "Blue"),
                            ("#a52a2a", "Brown"),
                            ("#ff7f50", "Coral"),
                            ("#00ffff", "Cyan"),
                            ("#ffd700", "Gold"),
                            ("#808080", "Gray"),
                            ("#0f0", "Green"),
                            ("#4b0082", "Indigo"),
                            ("#e6e6fa", "Lavender"),
                            ("#00ff00", "Lime"),
                            ("#ff00ff", "Magenta"),
                            ("#800000", "Maroon"),
                            ("#98ff98", "Mint"),
                            ("#000080", "Navy"),
                            ("#808000", "Olive"),
                            ("#ffa500", "Orange"),
                            ("#ffc0cb", "Pink"),
                            ("#800080", "Purple"),
                            ("#f00", "Red"),
                            ("#fa8072", "Salmon"),
                            ("#c0c0c0", "Silver"),
                            ("#008080", "Teal"),
                            ("#40e0d0", "Turquoise"),
                            ("#ee82ee", "Violet"),
                            ("#fff", "White"),
                            ("#ff0", "Yellow"),
                        ],
                        help_text="Background color for tag (e.g. #000 or 'blue')",
                        max_length=20,
                        null=True,
                        verbose_name="Background Color",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Wishlist",
                "verbose_name_plural": "Wishlists",
            },
        ),
    ]
