# Generated by Django 5.2.1 on 2025-07-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_offer",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
