# Generated by Django 5.2.1 on 2025-07-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0003_collection_is_offer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
