# Generated by Django 5.2.1 on 2025-07-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0004_delete_wishlist"),
        ("home", "0004_delete_featuredcollection"),
        ("product", "0003_remove_product_stock_remove_product_weight_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="bg_color",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="color",
        ),
        migrations.RemoveField(
            model_name="productcolor",
            name="product",
        ),
        migrations.DeleteModel(
            name="Collection",
        ),
        migrations.AddField(
            model_name="productcolor",
            name="product",
            field=models.ManyToManyField(
                related_name="product_colors", to="product.product"
            ),
        ),
    ]
