# Generated by Django 5.2.1 on 2025-07-20 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0005_remove_tag_bg_color_remove_tag_color_and_more"),
        ("product", "0004_remove_category_slug_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcolor",
            name="product_image",
        ),
        migrations.AddField(
            model_name="productcolor",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/colors/None/"
            ),
        ),
        migrations.AlterField(
            model_name="productcolor",
            name="color",
            field=models.CharField(
                choices=[
                    ("#f5f5dc", "Beige"),
                    ("#000", "Black"),
                    ("#00f", "Blue"),
                    ("#a52a2a", "Brown"),
                    ("#ff7f50", "Coral"),
                    ("#00ffff", "Cyan"),
                    ("#ffd700", "Gold"),
                    ("#808080", "Gray"),
                    ("#0f0", "Green"),
                    ("#4b0082", "Indigo"),
                    ("#e6e6fa", "Lavender"),
                    ("#00ff00", "Lime"),
                    ("#ff00ff", "Magenta"),
                    ("#800000", "Maroon"),
                    ("#98ff98", "Mint"),
                    ("#000080", "Navy"),
                    ("#808000", "Olive"),
                    ("#ffa500", "Orange"),
                    ("#ffc0cb", "Pink"),
                    ("#800080", "Purple"),
                    ("#f00", "Red"),
                    ("#fa8072", "Salmon"),
                    ("#c0c0c0", "Silver"),
                    ("#008080", "Teal"),
                    ("#40e0d0", "Turquoise"),
                    ("#ee82ee", "Violet"),
                    ("#fff", "White"),
                    ("#ff0", "Yellow"),
                ],
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="productcolor",
            name="product",
        ),
        migrations.AddField(
            model_name="productcolor",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colors",
                to="product.product",
            ),
            preserve_default=False,
        ),
    ]
