# Generated by Django 5.2.1 on 2025-07-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "features",
            "0006_remove_productcolor_product_image_productcolor_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
    ]
