# Generated by Django 5.2.1 on 2025-07-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Shipping"),
                    ("pickup", "In-store Pickup"),
                ],
                default="standard",
                max_length=20,
                verbose_name="Shipping Method",
            ),
        ),
    ]
