# Generated by Django 5.2.1 on 2025-07-22 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_shipping_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="postal_code",
        ),
    ]
