# Generated by Django 5.2.1 on 2025-07-22 03:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_remove_address_postal_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address_line",
        ),
        migrations.RemoveField(
            model_name="address",
            name="city",
        ),
        migrations.RemoveField(
            model_name="address",
            name="country",
        ),
        migrations.RemoveField(
            model_name="address",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="address",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Please write your address in detail, e.g., district, building number, apartment number, street name, and any additional details to facilitate order delivery. Example: 123 Nile St, Apt 4, Downtown, Cairo",
                verbose_name="Detailed Address",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="alternate_phone",
            field=models.CharField(
                blank=True,
                help_text="You can enter another Egyptian phone number for contact (optional). Example: 01123456789",
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with 010, 011, 012, or 015 and be 11 digits.",
                        regex="^(01[0125])[0-9]{8}$",
                    )
                ],
                verbose_name="Alternate Phone Number (optional)",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Cairo"),
                    ("GZ", "Giza"),
                    ("ALX", "Alexandria"),
                    ("ASN", "Aswan"),
                    ("AST", "Assiut"),
                    ("BNS", "Beni Suef"),
                    ("BH", "Beheira"),
                    ("IS", "Ismailia"),
                    ("MN", "Minya"),
                    ("MNF", "Monufia"),
                    ("MT", "Matrouh"),
                    ("KFS", "Kafr El Sheikh"),
                    ("DK", "Dakahlia"),
                    ("SHG", "Sohag"),
                    ("SHR", "Sharqia"),
                    ("PTS", "Port Said"),
                    ("DT", "Damietta"),
                    ("FYM", "Fayoum"),
                    ("GH", "Gharbia"),
                    ("KB", "Qalyubia"),
                    ("LX", "Luxor"),
                    ("WAD", "New Valley"),
                    ("SUZ", "Suez"),
                    ("SIN", "North Sinai"),
                    ("SIS", "South Sinai"),
                    ("QH", "Qena"),
                    ("RSH", "Red Sea"),
                ],
                help_text="Please select your governorate for more accurate shipping.",
                max_length=10,
                verbose_name="Governorate",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="phone",
            field=models.CharField(
                default=123,
                help_text="Please enter an Egyptian phone number starting with 010, 011, 012, or 015. Example: 01012345678",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with 010, 011, 012, or 015 and be 11 digits.",
                        regex="^(01[0125])[0-9]{8}$",
                    )
                ],
                verbose_name="Primary Phone Number",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(
                help_text="Please enter the recipient's full name as it appears on their ID for easier delivery.",
                max_length=100,
                verbose_name="Full Name",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Set as your default shipping address for faster checkout.",
                verbose_name="Is Default",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                help_text="The user who owns this address.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
