# Generated by Django 5.2.1 on 2025-07-22 03:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_address_address_line_remove_address_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["-is_default", "-updated_at"],
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.RemoveConstraint(
            model_name="address",
            name="unique_default_address_per_user",
        ),
        migrations.RemoveField(
            model_name="address",
            name="address",
        ),
        migrations.RemoveField(
            model_name="address",
            name="alternate_phone",
        ),
        migrations.AddField(
            model_name="address",
            name="address_line",
            field=models.TextField(default="", verbose_name="Detailed Address"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.CharField(
                default=12, max_length=100, verbose_name="City/Center"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Additional Notes"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="address",
            name="governorate",
            field=models.CharField(
                choices=[
                    ("C", "Cairo"),
                    ("GZ", "Giza"),
                    ("ALX", "Alexandria"),
                    ("ASN", "Aswan"),
                    ("AST", "Assiut"),
                    ("BNS", "Beni Suef"),
                    ("BH", "Beheira"),
                    ("IS", "Ismailia"),
                    ("MN", "Minya"),
                    ("MNF", "Monufia"),
                    ("MT", "Matrouh"),
                    ("KFS", "Kafr El Sheikh"),
                    ("DK", "Dakahlia"),
                    ("SHG", "Sohag"),
                    ("SHR", "Sharqia"),
                    ("PTS", "Port Said"),
                    ("DT", "Damietta"),
                    ("FYM", "Fayoum"),
                    ("GH", "Gharbia"),
                    ("KB", "Qalyubia"),
                    ("LX", "Luxor"),
                    ("WAD", "New Valley"),
                    ("SUZ", "Suez"),
                    ("SIN", "North Sinai"),
                    ("SIS", "South Sinai"),
                    ("QH", "Qena"),
                    ("RSH", "Red Sea"),
                ],
                max_length=10,
                verbose_name="Governorate",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Default Address"),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with 010, 011, 012, or 015 and be 11 digits.",
                        regex="^(01[0125])[0-9]{8}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
