# Generated by Django 5.2.1 on 2025-07-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_address_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Discount"
            ),
            preserve_default=False,
        ),
    ]
