# Generated by Django 5.2.1 on 2025-07-23 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_order_options_orderitem_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="address",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="address",
            name="phone",
        ),
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Full Name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Additional Notes"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(
                default=1,
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with 010, 011, 012, or 015 and be 11 digits.",
                        regex="^(01[0125])[0-9]{8}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
            preserve_default=False,
        ),
    ]
